log:
  level: debug
  path: app.log
network:
  ximalaya_ip: www.ximalaya.com
db:
  name: aws
  user: root
  password: password
gin:
  mode: release
aws_s3:
  region: ap-northeast-1
  access_key_id: 1qwded1
  access_key_secret: dwedew